#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wiki-go"
name = "Wiki-Go"
description.en = "Databaseless flat-file wiki platform"
description.fr = "Plate-forme wiki moderne sans base de données"

version = "1.8.8~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://wikigo.leomoon.com/"
code = "https://github.com/leomoon-studios/wiki-go"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "80M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "es", "fr", "it", "nl", "pl", "pt"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "wiki-go"
    amd64.url = "https://github.com/leomoon-studios/wiki-go/releases/download/v1.8.8/wiki-go-linux-amd64"
    amd64.sha256 = "6f4a4da3c11a8b1909f7e3968861914a89b49e92c2888a01a5c2b49d5477097e"
    arm64.url = "https://github.com/leomoon-studios/wiki-go/releases/download/v1.8.8/wiki-go-linux-arm64"
    arm64.sha256 = "c218896cd05829c600294514debcbe0e4b900843632f5d717dbb54e39770dbda"
    armhf.url = "https://github.com/leomoon-studios/wiki-go/releases/download/v1.8.8/wiki-go-linux-armv7"
    armhf.sha256 = "93176d706bb7c43ec9a4270d7b6c0a2bb431dcf50e0af8a846b1caf9f948f846"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "wiki-go-linux-amd64"
    autoupdate.asset.arm64 = "wiki-go-linux-arm64"
    autoupdate.asset.armhf = "wiki-go-linux-armv7"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
