#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wiki-go"
name = "Wiki-Go"
description.en = "Databaseless flat-file wiki platform"
description.fr = "Plate-forme wiki moderne sans base de données"

version = "1.8.9~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://wikigo.leomoon.com/"
code = "https://github.com/leomoon-studios/wiki-go"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "80M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "es", "fr", "it", "nl", "pl", "pt"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "wiki-go"
    amd64.url = "https://github.com/leomoon-studios/wiki-go/releases/download/v1.8.9/wiki-go-linux-amd64"
    amd64.sha256 = "e21d06baea87bc9e186a4b908f29eff71bbe5996174cc7d8810f705c916749ad"
    arm64.url = "https://github.com/leomoon-studios/wiki-go/releases/download/v1.8.9/wiki-go-linux-arm64"
    arm64.sha256 = "d545e8382b2a8bb3d701f50839ef4e43e61bf2d75ab833be64d91746474950b1"
    armhf.url = "https://github.com/leomoon-studios/wiki-go/releases/download/v1.8.9/wiki-go-linux-armv7"
    armhf.sha256 = "a269bfc80daed10b70187f166e5a222064011788beabe43997d625a0b0c1c543"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "wiki-go-linux-amd64"
    autoupdate.asset.arm64 = "wiki-go-linux-arm64"
    autoupdate.asset.armhf = "wiki-go-linux-armv7"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
